[build]
builder = "nixpacks"
buildCommand = "npm install --omit=dev --legacy-peer-deps && npm run build --workspace @terapia/api"
installCommand = "rm -rf node_modules && npm install --omit=dev --legacy-peer-deps"

[deploy]
startCommand = "node apps/api/dist/main.js"
restartPolicyType = "on_failure"
healthcheckPath = "/v1/health"
healthcheckTimeout = 120
